image: tmaier/docker-compose:latest

services:
  - docker:dind

.rspec:
  stage: test
  script:
    - docker-compose build
    - docker-compose run web yarn install --check-files
    - docker-compose run web rails db:create
    - docker-compose run web rails db:migrate
    - docker-compose up -d chrome
    - docker-compose run web rspec

deploy:
  stage: deploy
  script:
    - apk update && apk add git
    - git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git
    - git push -f heroku remotes/origin/develop:master