image: tmaier/docker-compose:latest

services:
  - docker:dind

.rspec:
  stage: test
  script:
    - docker-compose build
    - docker-compose run web yarn install --check-files
    - docker-compose run web rails db:create
    - docker-compose run web rails db:migrate
    - docker-compose up -d chrome
    - docker-compose run web rspec

deploy:
  stage: deploy
  script:
    - echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:login
    - docker build -t $HEROKU_IMAGE .
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:push web -a app-4q4t
    - docker push $HEROKU_IMAGE
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web -a app-4q4t
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run rails db:migrate -a app-4q4t
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run rails webpacker:install -a app-4q4t
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run rails assets:precompile -a app-4q4t
