image: tmaier/docker-compose:latest

services:
  - docker:dind

.rspec:
  stage: test
  script:
    - docker-compose build
    - docker-compose run web yarn install --check-files
    - docker-compose run web rails db:create
    - docker-compose run web rails db:migrate
    - docker-compose up -d chrome
    - docker-compose run web rspec

deploy:
  stage: deploy
  script:
    - apk update && apk add git
    # - git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME_TEST.git
    # - git add
    # - git commit -m "git push from gitlab"
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli login
    # - docker pull wingrunr21/alpine-heroku-cli
    # - docker container create -e HEROKU_API_KEY=$HEROKU_API_KEY --name heroku_container wingrunr21/alpine-heroku-cli
    # - docker exec heroku_container apk update && apk add git
    # - docker exec heroku_container 
    # - docker exec heroku_container git:remote -a test-4q4t
    # - docker exec heroku_conta
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli git:remote -a test-4q4t
    # - heroku git:remote -a test-4q4t
    # - git config --global user.email $EMAIL
    # - git config --global user.name $MY_NAME
    - git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME_TEST}.git
    - git branch -a
    # - git add .
    # - git commit -m "git push from gitlab."
    - git push -f heroku develop:master
    # - echo $HEROKU_API_KEY | docker login --username=_ --password-stdin $HEROKU_REGISTRY
    # - docker build -t $HEROKU_REGISTRY/$HEROKU_APP_NAME_TEST/release .
    # - docker push $HEROKU_IMAGE
    # - echo "$RAILS_MASTER_KEY" > config/master.key
    # - cat config/master.key
    # - docker build -t temp_image .
    # - docker images
    # - docker container create --name temp_container temp_image
    # - docker ps -a
    # - docker start temp_container
    # - docker ps -a
    # - docker exec temp_container rails assets:precompile RAILS_ENV=production
    # - docker stop temp_container
    # - docker ps -a
    # - docker commit temp_container $HEROKU_TEST_IMAGE_NAME
    # - docker images
    # - docker tag 4q4t_web $HEROKU_TEST_IMAGE_NAME
    # - docker images
    # - docker push $HEROKU_REGISTRY/$HEROKU_APP_NAME_TEST/release
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:push web -a test-4q4t
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli maintenance:on -a test-4q4t
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web release -a test-4q4t
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run rails db:migrate -a test-4q4t
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run yarn upgrade -a test-4q4t
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run rails webpacker:install -a test-4q4t
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run rails assets:precompile -a test-4q4t
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run rails webpacker:compile -a test-4q4t
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run rails webpacker:install -a test-4q4t
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run bin/webpack -a test-4q4t
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli maintenance:off -a test-4q4t
