image: tmaier/docker-compose:latest

services:
  - docker:dind

.rspec:
  stage: test
  script:
    - docker-compose build
    - docker-compose run web yarn install --check-files
    - docker-compose run web rails db:create
    - docker-compose run web rails db:migrate
    - docker-compose up -d chrome
    - docker-compose run web rspec

deploy:
  stage: deploy
  script:
    # - echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
    # - docker build -t $HEROKU_IMAGE .
    # - docker push $HEROKU_IMAGE
    - echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
    - docker-compose build web
    - docker tag 4q4t_web $HEROKU_TEST_IMAGE_NAME
    - docker images
    - docker push $HEROKU_TEST_IMAGE_NAME
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:push web -a test-4q4t
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli maintenance:on -a test-4q4t
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web -a test-4q4t
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run rails db:migrate -a test-4q4t
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run yarn install -a test-4q4t
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run rails webpacker:install -a test-4q4t
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run rails assets:precompile -a test-4q4t
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run rails webpacker:compile -a test-4q4t
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run rails webpacker:install -a test-4q4t
    # - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli run bin/webpack -a test-4q4t
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli maintenance:off -a test-4q4t
