version: '3'

services:
  db:
    image: postgres:12.0-alpine
    container_name: 4q4t_db
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    container_name: 4q4t_web
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - RAILS_SYSTEM_TESTING_SCREENSHOT=inline